baseURL = "https://isfj.dev"
title = "isfj.dev"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2025, isfjdev"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100

# Configuration Features
[params]
  description = "Software Engineer"
  header_title = "I’m isfjdev 👋"
  header_subtitle = "Software Engineer | VN"
  home_image = "/images/avatar.png"
  recent_posts = 5
  mainSections = ["posts", "post", "blog"]
  [params.style]
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "http://github.com/isfjdev"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/isfjdev"
  [[params.social]]
    fa_icon = "fab fa-x-twitter fa-1x"
    href = "https://x.com/isfjdev"
[[params.social]]
    fa_icon = "fas fa-envelope fa-1x"
    href = "mailto:isfjdev@gmail.com"
